openapi: 3.0.1
info:
  title: hl7-xml-service
  version: 0.1.0
servers:
- url: "{server}:{port}/convert"
  variables:
    server:
      default: http://localhost
    port:
      default: listenerPort
paths:
  /transform/xml:
    post:
      operationId: postTransformXml
      requestBody:
        content:
          application/xml:
            schema:
              type: object
        required: true
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                oneOf:
                - {}
                - $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
