[container.image]
repository="isuruh15-public" # Docker hub name
name="hl7_xml_template" # container name
tag="v0.1.0"

[settings]
buildImage=true # you can make this false if you don't want to build the image and you just need the Dockerfile